version: "3"

services:
  frontend:
    build:
      context: ./front-end
    container_name: frontend
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - ax4b
    depends_on:
      - backend
  backend:
    build:
      context: ./back-end
    container_name: backend
    restart: on-failure
    ports:
      - "3001:3001"
    networks:
      - ax4b

networks:
  ax4b:
    driver: bridge
